### ISSUE TITLE
Image orientation info appears not to be used leading to turned images

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#101]
By Shyamal on mailing list.

**Comment by misaochan** [comment]
Hm, did he post any further information? I haven't encountered this issue personally, both my portrait and landscape pics turn out okay.

**Comment by misaochan** [comment]
For instance, a portrait pic that I uploaded: https://commons.wikimedia.org/wiki/File:Tree_in_autumn_2.jpg . I guess I'll contact Shyamal to see exactly what he means.

**Comment by misaochan** [comment]
Shyamal's response to my post asking for details (I think he meant to post on the forum but just hit reply and  the email client only sent it to me, happened to me a few times too):

> Shyamal L <muscicapa@gmail.com>
> 11:23 PM (2 hours ago)
> 
> to me 
> Unfortunately this was on a Google Nexus 5 that no longer runs. The images were fine on Commons. It seems to be something only on the phone preview. I am sure this will be gone when you make other exit related fixes. When is the app available again?
 
I think he means that the images are always displaying as 'landscape' on the main screen of the app. I think it was probably designed that way for aesthetic purposes, otherwise the grid would not look uniform. Is this something we want to change?

**Comment by nicolas-raoul** [comment]
Would you mind posting a screenshot of how Tree_in_autumn_2.jpg looks in the app? Thanks :-)

**Comment by misaochan** [comment]
Main activity:

![device-2016-07-11-main](https://cloud.githubusercontent.com/assets/3611199/16720600/0cd92a70-478c-11e6-9423-41c7ff0294ef.png)

Detailed view:

![device-2016-07-11-detail](https://cloud.githubusercontent.com/assets/3611199/16720601/139d48dc-478c-11e6-9714-88cef285255c.png)

**Comment by nicolas-raoul** [comment]
It looks perfect like this, I would say :-)

**Comment by misaochan** [comment]
Haha yeah, I figured so too. All good then. :)
