### ISSUE TITLE
Description / License / Categories empty

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#12]
When clicking on a picture.
Either fix or remove

**Comment by misaochan** [comment]
I had a similar problem, but it oddly resolved after clearing app data and cache (on Samsung Galaxy S4).

**Comment by misaochan** [comment]
I did a bit more testing and it seems that this only happens with newly-uploaded pics. Pics that were uploaded a while ago (maybe prior to last restart?) are fine. Not sure why....

**Comment by misaochan** [comment]
@nicolas-raoul This bug is quite interesting. I found the issue: In the displayMediaDetails() method of MediaDetailFragment.java, it handles images differently depending on whether the actualUri of the image being loaded starts with http:// (which means it's downloaded from commons, e.g. https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Takoyaki_2.jpg/640px-Takoyaki_2.jpg
) or anything else (usually device storage). It displays the desc/license/cats if it starts with http:// and not if it starts with anything else.

So I copied the code for displaying the desc/license/cats into the 'else' branch (see #160), and those fields aren't empty anymore. The catch is, the desc just says 'No description' and the cats says 'non selected'. I'm guessing this is because desc/license/cats aren't stored at all with the image on device storage. 

I'm not sure why some images are retrieved from the internet and some are retrieved from device storage. How do you think we should proceed with this? Do we want to try and make the app load everything from the internet? Or just remove the fields entirely?

**Comment by nicolas-raoul** [comment]
I believe desc/license/cats should be downloaded from the Internet every time, since they are often modified.
I believe that the fields are useful, especially if we add edition capabilities in the future (#161)

**Comment by misaochan** [comment]
I don't know if they can be downloaded from the internet without also downloading the associated image. As in, I don't think we can just 'match' them with the image on the device storage. Would it be worth the bandwidth tradeoff if we make it download from the internet all the time?

**Comment by misaochan** [comment]
Done at #162

**Comment by nicolas-raoul** [comment]
How about adding a field linking to the online image (in Media.java?) and
setting it at the right place?

Loading images everytime would probably increase bandwidth usage a lot,
since images are displayed everytime the app is opened, and most people
probably upload using the app only :-/

**Comment by misaochan** [comment]
Hm, this doesn't affect the images displayed in ContributionsList (the main activity when people open the app). It only loads the image when the user taps a particular contribution to display the title, desc, cats etc. 

If we just link to the online image, they will still need to download it to view it, right?

**Comment by nicolas-raoul** [comment]
Ah OK! If only after tapping a particular image then it is perfectly OK
then, thanks for the explanation :-)

**Comment by misaochan** [comment]
Fixed via #162
