### ISSUE TITLE
Assign a tag to upload and edit actions made with the app

### ISSUE THREAD

**Issue by whym** [nicolas-raoul/apps-android-commons#143]
[Edit tags](https://commons.wikimedia.org/wiki/Special:Tags) help classifying edits, for purposes including providing usage statistics etc. We could [try classifying by the edit summary](https://quarry.wmflabs.org/query/10587), but edit tags are cleaner and more natural to the MediaWiki ecosystem.

Mobile Web is using `mobile web edit` and `mobile edit`. We could probably use `mobile app edit` and `mobile edit`.

**Comment by nicolas-raoul** [comment]
Good idea!
Also, it seems that all images uploaded by the app automatically belong to this category: https://commons.wikimedia.org/wiki/Category:Uploaded_with_Mobile/Android

**Comment by whym** [comment]
Yes, that category is also useful. It can be used to answer questions like "How many files exist on Commons uploaded with the app". Deleted files will not be counted (at least, not in a straightforward manner).

Edit tags are for individual edits. (I've now clarified it in the title.) They can be used to answer questions like "how many uploads were done with the app". Upload logs and associated tags remain visible after the file question is deleted.

**Comment by whym** [comment]
It appears like MediaWiki adds these tags based on the user agent string. E.g. it detects the Wikipedia app by the "WikipediaApp/" line: https://github.com/wikimedia/mediawiki-extensions-MobileApp/blob/master/MobileApp.hooks.php#L27

It's fairly easy to make it support Commons app. But, I would like to have a buy-in that we are going to use `Commons/` stably. Although next to `WikipediaApp/` it would seem somewhat strange, I would suggest that changing the user agent string would create unnecessary confusion.

What do you think?

**Comment by nicolas-raoul** [comment]
Interesting find!
Do we need to differentiate between Android and iOS? The Android app is diverging very fast, they are not the same app anymore.
If not, I think that `Commons/` is the best name to use. Even though it is developed by volunteers, it is the only Commons app and will probably be so for a while.
I agree with you that we must take a decision and then stick to it.
For the tag I would suggest `commons app edit` because edits from the Wikipedia app are made by a very different public.

**Comment by whym** [comment]
Let me be clearer - I meant to ask whether we want (or expect) to change the current user agent string - it *is* already `Commons/` + version number. (It's defined in `CommonsApplication.java`.)  I didn't see a strong case for changing it to something else, but just wanted to make sure. If `Commons/` is fine, no action is needed.

**Comment by whym** [comment]
>  For the tag I would suggest commons app edit because edits from the Wikipedia app are made by a very different public.

I would prefer "mobile app edit". Not against "commons app edit", but reusing existing tags is easier and causes no confusion as far as I can see. Wikipedia app works for wikipedia.org only, and Commons app works for commons.wikimedia.org only.

Anyway, I'll try submitting a patch and see what the maintainers of the MediaWiki extension say.

**Comment by jayvdb** [comment]
> Wikipedia app works for wikipedia.org only, and Commons app works for commons.wikimedia.org only.

Doesnt the Wikipedia app include a "upload to Commons" feature?

**Comment by nicolas-raoul** [comment]
I also remember seeing Commons pictures being uploaded via the Wikipedia app.
The feature might have been disabled now, but it might be re-enabled in the future.

Seeing https://commons.wikimedia.org/wiki/Special:Tags I notice the following tags:

- `mobile edit`	(Edit made from mobile (web or app)) 97,176 changes
- `mobile web edit` (Edit made from mobile web site) 	45,268 changes
- `mobile app edit` (Edits made from mobile apps) 0 changes

I wonder why the ambiguous `mobile edit` tag exists, I guess it is historical and I guess it has been superseded by the split `mobile web edit` and `mobile app edit` tags _after_ the Commons upload feature was removed from the Wikipedia app, which would explain why `mobile app edit` has zero edits.

So I would still favour a separate `commons app edit` because it will help when/if the Wikipedia app decides to re-enable their upload feature. That being said, a `mobile app edit` tag wouls still be better than no tag at all, so feel free to get it working the way you want :-) Cheers!

**Comment by whym** [comment]
Now deployed.
https://commons.m.wikimedia.org/w/index.php?title=Special:RecentChanges&tagfilter=mobile+app+edit

**Comment by nicolas-raoul** [comment]
Wonderful!
So, in practice the images listed there are uploaded mostly by our app, I guess?

**Comment by whym** [comment]
Yes, all I checked were with the comment "using Android Commons app" or "Via Commons Mobile App".

**Comment by whym** [comment]
Just noticed that edits via Commons Reloaded (iOS) are also identified as "mobile app edit".

https://commons.wikimedia.org/w/index.php?title=File:Casa_orlandai_juliol_2016.jpg&action=history
https://commons.wikimedia.org/w/index.php?title=Special:RecentChangesLinked&limit=250&target=Category%3AUploaded_with_Commons_Reloaded

So there are two apps using the tag. I don't see it as a problem though - both apps make themselves clear by the edit summary ("Uploaded with Commons Reloaded for iOS" and "Uploaded using Android Commons app").
