### ISSUE TITLE
"Template:According to EXIF data" analyzing EXIF data incorrectly

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#72]
Reported by Riley_Huntley on Phabricator (https://phabricator.wikimedia.org/T127624):

https://commons.wikimedia.org/wiki/File:William_Hill_Estate_Vineyards_-_Sarah_Stierch_2.jpg and https://commons.wikimedia.org/wiki/File:Tortoises_at_the_Minnesota_Zoo.jpg show a correct EXIF data, yet "{{According to EXIF data|1969-xx-xx}}" or "{{According to EXIF data|1970-xx-xx}}" will be automatically added to the information template. This has effected 2,000~ files and counting.

**Comment by misaochan** [comment]
Plan: Set to upload date if date is 1969 or 1970.

**Comment by domdomegg** [comment]
Done in #123 

Should we try and get it to say just the date, not "[according to EXIF data](https://github.com/nicolas-raoul/apps-android-commons/blob/master/commons/app/src/main/java/fr/free/nrw/commons/contributions/Contribution.java#L141)"? Or maybe use [{{Upload date}}](https://commons.wikimedia.org/wiki/Template:Upload_date) instead? If so, I'm not sure how we could go about that - probably checking some new variable in contribution to see whether the upload date is used instead of EXIF date?

**Comment by misaochan** [comment]
Not sure about that, tagging @nicolas-raoul to ask. :)

Also, just noticed that the dates in the 2 images linked are actually 31 Dec 1969. How is that happening when Date(0) is 1 Jan 1970? Is there a way we can test for this as well?

**Comment by domdomegg** [comment]
Just seen that... weird. Maybe if <=0? Will be home soon.

**Comment by misaochan** [comment]
Might be a timezone issue: http://www.rachaelarnold.com/dev/archive/why-is-date-returning-wrong

I submitted a PR #125

**Comment by misaochan** [comment]
Appears to be fixed for now.
